import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/navbar";
import Providers from "@/components/providers";

const vazir = Vazirmatn({
  subsets: ['latin'],
  weight: ['600'],
  variable: "--font-vazir"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={cn(
        "relative h-full font-vazir antialiased",
        vazir.variable
      )}>
        <main className="relative flex flex-col min-h-screen">
          <Providers>
            <Navbar />
            <div className="flex-grow flex-1">
              {children}
            </div>
          </Providers>
        </main>
      </body>
    </html>
  );
}
